// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgycuyrkkqwwegazgvcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndneWN1eXJra3F3d2VnYXpndmNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MTM1MTMsImV4cCI6MjA3NjM4OTUxM30.tl7O8mzSO0FlepRJO5c7IBMapnGP-z-jn74wLf643co";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});