// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// CORREÇÃO DE SEGURANÇA: Usar variáveis de ambiente ao invés de hardcoded
let SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
let SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// CORREÇÃO TEMPORÁRIA: Removido throw error para não quebrar aplicação
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('⚠️ Variáveis de ambiente do Supabase não configuradas');
  console.error('Verifique se VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY estão definidas no arquivo .env');
  // Usar valores hardcoded como fallback temporário
  SUPABASE_URL = "https://wgycuyrkkqwwegazgvcb.supabase.co";
  SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndneWN1eXJra3F3d2VnYXpndmNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MTM1MTMsImV4cCI6MjA3NjM4OTUxM30.tl7O8mzSO0FlepRJO5c7IBMapnGP-z-jn74wLf643co";
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});